@startuml
title 04 - Import Topics from Businesses

actor GraduationThesisManager
participant TopicImportController
participant TopicImportService
database Topic

GraduationThesisManager -> TopicImportController : uploadTopicFile(file)
TopicImportController -> TopicImportService : parseAndValidateTopics(file)
TopicImportService -> Topic : createMany(validatedTopics)
Topic --> TopicImportService : success
TopicImportService -> TopicImportController : result
TopicImportController -> GraduationThesisManager : showImportStatus()
@enduml