@startuml
title 07 - Review Council Creation

actor GraduationThesisManager
participant CouncilController
participant CouncilService
database Council
database CouncilMember

GraduationThesisManager -> CouncilController : createCouncil(councilData)
CouncilController -> CouncilService : createCouncilAndMembers()
CouncilService -> Council : create(councilData)
Council --> CouncilService : councilCreated
CouncilService -> CouncilMember : createMany(members)
CouncilMember --> CouncilService : membersCreated
CouncilService -> CouncilController : councilWithMembers
CouncilController -> GraduationThesisManager : displayCouncilDetails()
@enduml