@startuml
title 08 - Reviewer Assignment

actor GraduationThesisManager
participant ReviewAssignmentController
participant ReviewAssignmentService
database ReviewAssignment

GraduationThesisManager -> ReviewAssignmentController : assignReviewers(data)
ReviewAssignmentController -> ReviewAssignmentService : createAssignments()
ReviewAssignmentService -> ReviewAssignment : createMany(data)
ReviewAssignment --> ReviewAssignmentService : success
ReviewAssignmentService -> ReviewAssignmentController : assignmentResult
ReviewAssignmentController -> GraduationThesisManager : displayResult()
@enduml