name: Deploy to VPS with MySQL 

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t hoangleuleu/project-management-system-mysql:v1 .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push hoangleuleu/project-management-system-mysql:v1

  deploy:
    name: Deploy to VPS with MySQL
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST_PRODUCTION }}
          username: ${{ secrets.USERNAME_PRODUCTION }}
          password: ${{ secrets.PASSWORD_PRODUCTION }}
          port: ${{ secrets.PORT_PRODUCTION }}
          script: |
            printf "%s\n" "${{ secrets.ENV_PROD }}" > .env
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            docker pull hoangleuleu/project-management-system-mysql:v1
            docker rm -f project_management_container || true
            docker run -d -p 6969:3000 \
              --name project_management_container \
              --env-file .env \
              --add-host=host.docker.internal:host-gateway \
              hoangleuleu/project-management-system-mysql:v1
            docker image prune -f
            docker ps
